[package]
name = "dwade"
version = "0.1.0"
authors = ["Michał Krawczyk <krawczyk.michal93@gmail.com>"]
edition = "2018"

[features]
default = ["debug_logs"]
debug_logs = []

[dependencies]
chrono = "0.4"
